---
- name: install epel
  yum:
    name: 
      #- epel-release
      - python-pip
      - MySQL-python
      - php
      - php-mysql
      - git
    state: present

- name: Make sure pymysql is present
  pip:
   name: pymysql

- name: Deploy and Configure web
  yum:
     name: httpd
     state: present
  notify: Start httpd web server

- name: cloning a git repo
  git:
     repo: 'https://github.com/kodekloudhub/learning-app-ecommerce.git'
     dest: /var/www/html/
  ignore_errors: True

- name: Changing index directory
  template:
     src: httpd.conf.j2
     dest: /etc/httpd/conf/httpd.conf

- name: Changing host in index.php
  template:
     src: index.php.j2
     dest: /var/www/html/index.php


- name: Deploy and Configure Database
  yum:
     name: mariadb-server
     state: present
  notify: Start Database



- name: Create new user "{{ db_user }}"
  mysql_user:
     host: "{{db_host}}"
     name: "{{ db_user }}"
     password: "{{ db_pass }}"
     priv: '*.*:ALL,GRANT'
     state: present


- name: Create a new database with name "{{ db_name }}"
  mysql_db:
     name: "{{ db_name }}"
     state: present

- name: import ecom-table sql file
  mysql_db:
     state: import
     name: "{{ db_name }}"
     target: db-load-script.sql
  ignore_errors: True
