---
# handlers file for web_config_role
- name: Start httpd web server
  service:
     name: httpd
     state: started
     enabled: yes

- name: Start Database
  service:
     name: mariadb
     state: started
     enabled: yes
